-- Setting up the lazy loader
--require('packages')
require('lpackages')
require('essentials')
require('_lualine')
require('autocomplete')
require('_blankline')
require('_lspconfig')
require('_lspcalightbulb')
require('_telescope')
require('_treesitter')
require('_diagnostics')
require('_theme')
--vim.cmd('colorscheme kanagawa')
